"""DASS-21 item definitions and paraphrase lists for NLP symptom matching."""

DASS_ITEMS = [
    {
        "id": 1,
        "category": "Depression",
        "label": "I felt that I had nothing to look forward to",
        "phrases": [
            "nothing to look forward to",
            "no hope for the future",
            "hopeless about the future",
            "nothing to look forward",
            "no future to look forward",
            "feel hopeless",
            "felt hopeless",
            "feeling hopeless",
        ],
    },
    {
        "id": 2,
        "category": "Depression",
        "label": "I was unable to become enthusiastic about anything",
        "phrases": [
            "unable to become enthusiastic",
            "can't get enthusiastic",
            "cannot get enthusiastic",
            "no enthusiasm",
            "lack of enthusiasm",
            "not enthusiastic",
            "feel unmotivated",
            "felt unmotivated",
            "unmotivated about anything",
        ],
    },
    {
        "id": 3,
        "category": "Depression",
        "label": "I feel like I am not worth anything as a person",
        "phrases": [
            "not worth anything",
            "feel worthless",
            "felt worthless",
            "feeling worthless",
            "worthless as a person",
            "no self worth",
            "not worth much",
            "feel like i am worthless",
        ],
    },
    {
        "id": 4,
        "category": "Depression",
        "label": "I believe that life is meaningless",
        "phrases": [
            "life is meaningless",
            "life feels meaningless",
            "meaningless life",
            "feel life is meaningless",
            "felt life is meaningless",
            "no meaning in life",
            "life has no meaning",
        ],
    },
    {
        "id": 5,
        "category": "Depression",
        "label": "I couldn't seem to experience any positive feelings at all",
        "phrases": [
            "no positive feelings",
            "can't experience positive feelings",
            "cannot experience positive feelings",
            "unable to feel positive",
            "no good feelings",
            "feel nothing positive",
            "felt nothing positive",
            "numb to positive feelings",
        ],
    },
    {
        "id": 6,
        "category": "Depression",
        "label": "I found it difficult to work up the initiative to do things",
        "phrases": [
            "difficult to work up initiative",
            "hard to get motivated",
            "difficult to get started",
            "no initiative",
            "lack initiative",
            "can't get started",
            "cannot get started",
            "struggle to start tasks",
        ],
    },
    {
        "id": 7,
        "category": "Depression",
        "label": "I was downhearted and blue",
        "phrases": [
            "downhearted and blue",
            "feel downhearted",
            "felt downhearted",
            "feeling downhearted",
            "feel blue",
            "felt blue",
            "feeling blue",
            "feel sad",
            "felt sad",
            "feeling sad",
            "feel down",
            "felt down",
            "feeling down",
        ],
    },
    {
        "id": 8,
        "category": "Anxiety",
        "label": "I was aware of dryness of my mouth",
        "phrases": [
            "dryness of my mouth",
            "dry mouth",
            "mouth feels dry",
            "mouth was dry",
            "aware of dry mouth",
            "dryness in my mouth",
        ],
    },
    {
        "id": 9,
        "category": "Anxiety",
        "label": "I experienced breathing difficulty (e.g. excessively rapid breathing, breathlessness in the absence of physical exertion)",
        "phrases": [
            "breathing difficulty",
            "difficulty breathing",
            "hard to breathe",
            "difficult to breathe",
            "shortness of breath",
            "breathless",
            "breathlessness",
            "rapid breathing",
            "can't catch my breath",
            "cannot catch my breath",
        ],
    },
    {
        "id": 10,
        "category": "Anxiety",
        "label": "I experienced trembling (e.g. in the hands)",
        "phrases": [
            "experienced trembling",
            "hands trembling",
            "trembling hands",
            "feel trembling",
            "felt trembling",
            "shaking hands",
            "hands shaking",
            "body trembling",
        ],
    },
    {
        "id": 11,
        "category": "Anxiety",
        "label": "I was worried about situations in which I might panic and make a fool of myself",
        "phrases": [
            "worried about panic",
            "might panic",
            "afraid of panicking",
            "worried about making a fool",
            "fear of embarrassing myself",
            "worried i might panic",
            "anxious about panicking",
        ],
    },
    {
        "id": 12,
        "category": "Anxiety",
        "label": "I felt I was close to panic",
        "phrases": [
            "close to panic",
            "near panic",
            "almost panicking",
            "on the verge of panic",
            "feel close to panic",
            "felt close to panic",
            "about to panic",
        ],
    },
    {
        "id": 13,
        "category": "Anxiety",
        "label": "I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)",
        "phrases": [
            "heart rate increase",
            "heart racing",
            "racing heart",
            "heart pounding",
            "pounding heart",
            "heart missing a beat",
            "palpitations",
            "aware of my heart",
            "heart beating fast",
            "without physical exertion",
        ],
    },
    {
        "id": 14,
        "category": "Anxiety",
        "label": "I felt scared without any good reason",
        "phrases": [
            "scared without reason",
            "scared for no reason",
            "feel scared",
            "felt scared",
            "feeling scared",
            "frightened for no reason",
            "unexplained fear",
            "afraid without reason",
        ],
    },
    {
        "id": 15,
        "category": "Stress",
        "label": "I found it hard to wind down",
        "phrases": [
            "hard to wind down",
            "difficult to wind down",
            "can't wind down",
            "cannot wind down",
            "unable to wind down",
            "trouble winding down",
            "struggle to wind down",
        ],
    },
    {
        "id": 16,
        "category": "Stress",
        "label": "I tended to over-react to situations",
        "phrases": [
            "over-react",
            "overreact",
            "over react",
            "overreacting",
            "over reacting",
            "react too strongly",
            "overreact to situations",
        ],
    },
    {
        "id": 17,
        "category": "Stress",
        "label": "I felt that I was using a lot of nervous energy",
        "phrases": [
            "lot of nervous energy",
            "using nervous energy",
            "full of nervous energy",
            "feel nervous energy",
            "felt nervous energy",
            "wired and tense",
            "on edge",
        ],
    },
    {
        "id": 18,
        "category": "Stress",
        "label": "I found myself getting agitated",
        "phrases": [
            "getting agitated",
            "feel agitated",
            "felt agitated",
            "feeling agitated",
            "become agitated",
            "easily agitated",
            "agitation",
        ],
    },
    {
        "id": 19,
        "category": "Stress",
        "label": "I found it difficult to relax",
        "phrases": [
            "difficult to relax",
            "hard to relax",
            "can't relax",
            "cannot relax",
            "unable to relax",
            "trouble relaxing",
            "struggle to relax",
        ],
    },
    {
        "id": 20,
        "category": "Stress",
        "label": "I was intolerant of anything that kept me from getting on with what I was doing",
        "phrases": [
            "intolerant of interruptions",
            "can't stand interruptions",
            "impatient when interrupted",
            "intolerant of anything",
            "frustrated when interrupted",
            "kept from getting on",
            "can't get on with what i was doing",
        ],
    },
    {
        "id": 21,
        "category": "Stress",
        "label": "I felt that I was rather touchy",
        "phrases": [
            "rather touchy",
            "feel touchy",
            "felt touchy",
            "feeling touchy",
            "easily irritated",
            "quick to anger",
            "short tempered",
            "irritable",
            "feel irritable",
            "felt irritable",
        ],
    },
]

# General category keywords (single/multi-word) mapped to items via separate matcher entries
_CATEGORY_PHRASES = {
    "Depression": ["depressed", "feel depressed", "depression", "feel depressed"],
    "Anxiety": ["anxious", "feel anxious", "anxiety", "feel anxiety", "worried", "feel worried"],
    "Stress": ["stressed", "feel stressed", "stress", "under stress", "feel stress"],
}

# Map general category phrases to representative item ids
_CATEGORY_PHRASE_ITEM = {
    "Depression": 7,
    "Anxiety": 14,
    "Stress": 19,
}

ANTONYM_PHRASES = {
    "Depression": [
        "happy",
        "feel happy",
        "felt happy",
        "joyful",
        "cheerful",
        "hopeful",
        "enthusiastic",
        "content",
        "satisfied",
    ],
    "Anxiety": [
        "calm",
        "feel calm",
        "relaxed",
        "feel relaxed",
        "confident",
        "feel confident",
        "at ease",
        "feel at ease",
    ],
    "Stress": [
        "peaceful",
        "feel peaceful",
        "laid-back",
        "carefree",
        "serene",
        "unbothered",
    ],
}

# Representative item when antonym is negated (low mood / tension signal)
ANTONYM_ITEM_ID = {
    "Depression": 5,
    "Anxiety": 14,
    "Stress": 19,
}
